config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'admin/new/signup'}

  root                  'pages#home'
  get   'about'    =>   'pages#about'
  get   'contact'  =>   'pages#contact'
  get   'news'     =>   'pages#news'
  get   'help'     =>   'pages#help'

  resources :users
  resources :courses do
    resources :coursesemesters do
        end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role?
      can :manage, :all if user.role == "admin"
    else
      can :read, :all
      can :update, User do |nothing|
        nothing.user.role == user
      end
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  has_many   :coursesemesters
end

app/models/user.rb
class User < ActiveRecord::Base

  ROLES = %w[admin teacher student]

  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :courses,              dependent: :destroy
  has_many :takes,                dependent: :destroy
  has_many :coursesessions,       dependent: :destroy
  has_many :sessionenrolls,       dependent: :destroy
  has_many :coursesemesters,      dependent: :destroy
  has_many :semestersubjects,     dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end

  def after_sign_in_path_for(user)
    @user
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :role)}
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :current_password,
                                                     :password, :password_confirmation, :role, :username)}
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  # http_basic_authenticate_with name: "administratorofroas.com", password: "abcde.1234"
  def index
    @courses = Course.all
    @user = current_user
  end

  def show
    @coursesemester = Coursesemester.new
  end

  def new
    @course = Course.new
    @user = current_user
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to courses_url, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: courses_url.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to courses_url, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: courses_url.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_course
      @course = Course.find(params[:id])
      @user = current_user
    end

    def course_params
      params.require(:course).permit(:title, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = current_user
  end

  def about
    @user = current_user
    @users = User.all
  end

  def contact
  end

  def news
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
    @user = User.find_by(params[:id])
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    # @course = Course.find(params[:course_id])
    # @coursesemester = Coursesemester.find(params[:coursesemester_id])
    # @user = current_user
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<div class="row">
  <div class="col-xs-6">
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :title, class: "form-control", placeholder: "Enter Course Title" %>
  <br>
    <%= f.submit "Add Course", class: "btn btn-primary" %>
    <%= link_to 'Back', courses_path, class: "btn btn-default" %>

<% end %>
  </div>
</div>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h2>Listing Courses</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= link_to 'Show', course, class: "btn btn-primary btn-sm" %>
        <%= link_to 'Edit', edit_course_path(course), class: "btn btn-success btn-sm" %>
        <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' },
                                                                class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path, class: "btn btn-default" %>

app/views/courses/new.html.erb
<h2>Add New Course</h2>
<br>
<%= render 'form' %>

app/views/courses/show.html.erb
<%= @course.title %>
<table class="table">

<ol>
<% @course.coursesemesters.each do |semester| %>
  <tr>
    <td><%= link_to semester.name, course_coursesemester_path(@course, semester) %></td>
    <td><%= link_to 'Destroy', [@course, semester], method: :delete, 
                        data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
  </tr>
<% end -%>
</ol>
</table>
<hr>

<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
  Add Semester
</button>
<br><br>
<div class="collapse" id="collapseExample">
  <div class="well">
    <%= render 'coursesemesters/form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ROAS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'shared/header' %>
<%= render 'shared/notice_and_alert' %>

<div class="container">
  <div class="row">
    <div class="col-xs-4 col-md-2"></div>
    <div class="col-xs-12 col-md-8"><%= yield %></div>
  </div>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/help.html.erb
<h1>Help</h1>

app/views/pages/home.html.erb
<h1>Home</h1>

app/views/pages/news.html.erb
<h1>News</h1>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <li><%= link_to "ROAS", "/", class: "navbar-brand"  %></li>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav ">
        <%= render 'shared/top_nav1' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= render 'shared/username_email' %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
            aria-expanded="false">Account <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
          <% if @user.username.present? %>
            <li><%= link_to current_user.email %></li>
            <li role="separator" class="divider"></li>
          <% end %>
            <li><%= link_to "Profile", user_path(@user) %></li>
            <li><%= link_to "Setting", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notice_and_alert.html.erb
<div class="row">
  <div class="col-xs-6 col-md-offset-3">
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= alert %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_top_nav1.html.erb
<% if user_signed_in? %>
  <% if @user.role == "admin" %>
    <li><%= link_to "Courses",      courses_path %></li>
    <li><%= link_to "Session" %></li>
    <li><%= link_to "Enrollment" %></li>
  <% end %>
  <% if @user.role == "admin" %>
    <li><%= link_to "All Users", users_path %></li>
  <% else %>
    <li><%= link_to "Class Fellows List", users_path %></li>
  <% end %>
<% else %>
  <li class="active"><%= link_to "Home", "/" %><span class="sr-only">(current)</span></li>
  <li><%= link_to "About",    about_path %></li>
  <li><%= link_to "Contact",  contact_path %></li>
  <li><%= link_to "News",     news_path %></li>
  <li><%= link_to "Help",     help_path %></li>
<% end %>

app/views/shared/_username_email.html.erb
<% if @user.username.present? %>
  <li><%= link_to current_user.username, current_user %></li>
<% else %>
  <li><%= link_to current_user.role.titleize %></li>
  <li><%= link_to current_user.email %></li>
<% end %>

app/views/users/_first_semester.html.erb
<td>
<% coursesemester.semestersubjects.each do |subject| %>
  <%= subject.name %>
<% end -%>
</td>

app/views/users/_forth_semester.html.erb
<td><strong>4th Semester</strong></td>
<tr>
  <td>Networking (Elective I)</td>
  <td>Web Engineering</td>
  <td>Computer Organization and Assembly Language (Elective II)</td>
</tr>

app/views/users/_second_semester.html.erb
<td><strong>2nd Semester</strong></td>
<tr>
  <td>Networking</td>
  <td>Algorithum</td>
  <td>Compiler Construction</td>
  <td>Software Engrineeing</td>
  <td>Computer Architeture</td>
  <td>Operating System</td>
</tr>

app/views/users/_third_semester.html.erb
<td><strong>3rd Semester</strong></td>
<tr>
  <td>Artificial Inteligence</td>
  <td>Management Information System</td>
  <td>Computer Graphics</td>
  <td>Algorithum Design and Anaylsis</td>
  <td>C Sharp</td>
</tr>

app/views/users/index.html.erb
<h2>Users List</h2>
<% if current_user && @user.role == "admin" %>
<table class="table">
  <thead>
    <tr>
      <th>User Name</th>
      <th>User Role</th>
      <th>User Email</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user %></td>
      <td><%= user.role.titleize %></td>
      <td><%= user.email %></td>
      <td>
        <span class="btn-group btn-group-sm" role="group">
          <%= link_to "Show", user_path(user), class: "btn btn-primary" %>
        </span>
        <span class="btn-group btn-group-sm" role="group">
          <%= link_to "Edit", edit_user_registration_path, class: "btn btn-success" %>
        </span>
        <span class="btn-group btn-group-sm" role="group">
          <%= link_to "Delete", user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </span>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% else %>

<!-- Other then Admin Users -->

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Course</th>
      <th>Session</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <% if user.role == current_user.role %>
        <tr>
          <td><%= link_to user.username, user %></td>
          <td><%= user.email %></td>
          <td>
            <span class="btn-group btn-group-sm" role="group">
              <%= link_to "Show", user_path(user), class: "btn btn-primary" %>
            </span>
          <% if current_user == user %>
            <span class="btn-group btn-group-sm" role="group">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-success" %>
            </span>
          <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h2><%= @user.username %></h2>
    <table class="table">
      <tr>
        <td><strong>Role:</strong></td>
        <td><%= @user.role.titleize %></td>
      </tr>
      <tr>
        <td><strong>Email:</strong></td>
        <td><%= @user.email %></td>
      </tr>
      <% @user.sessionenrolls.each do |enroll| %>
      <tr>
        <td><strong>Session:</strong></td>
        <td><%= enroll.coursesession.name %></td>
      </tr>
      <% end %>

      <tr>
      </tr>
    </table>
  </div>
  <div class="col-md-12">
    <% @user.takes.each do |take| %>
      <br><span class="updown-line">
      <strong>Course:</strong>
      <%= take.course.title %>
      </span><br>
    <% take.course.coursesemesters.each do |coursesemester| %><br>
      <strong><%= coursesemester.name %></strong><br>
    <% coursesemester.semestersubjects.each do |subject| %>
      <%= link_to subject.name, course_coursesemester_semestersubject_path(coursesemester, coursesemester, subject) %> |
    <% end -%>
    <% end -%>
    <% end %>
  </div>
</div>